esphome:
  name: kickstart-bk7231t

bk72xx:
  board: generic-bk7231t-qfn32-tuya

logger:
web_server:
captive_portal:
mdns:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
