esphome:
  name: kickstart-rtl8710bn-2mb-788k

rtl87xx:
  board: generic-rtl8710bn-2mb-788k

logger:
web_server:
captive_portal:
mdns:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
