esphome:
  name: kickstart-esp32

esp32:
  board: esp32dev

logger:
web_server:
captive_portal:
mdns:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
