esphome:
  name: kickstart-esp8266

esp8266:
  board: esp01_1m

logger:
web_server:
captive_portal:
mdns:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
