substitutions:
  name: kickstart-bk7231t
  import_url: github://libretiny-eu/esphome-kickstart/yaml/import-bk7231t.yaml@master

packages:
  base: !include kickstart-base.yaml

bk72xx:
  board: generic-bk7231t-qfn32-tuya
  loglevel: debug

select:
  - platform: template
    id: !extend pin
    options:
      - Select PIN
      - P0 / UART2_TX / I2C2_SCL
      - P1 / UART2_RX / I2C2_SDA
      - P6 / PWM0
      - P7 / PWM1
      - P8 / PWM2
      - P9 / PWM3
      - P10 / UART1_RX
      - P11 / UART1_TX
      - P14 / SCK
      - P15 / CS
      - P16 / MOSI
      - P17 / MISO
      - P20 / I2C1_SCL / TCK
      - P21 / I2C1_SDA / TMS
      - P22 / TDI
      - P23 / TDO / ADC3
      - P24 / PWM4
      - P26 / PWM5
      - P28
