substitutions:
  name: kickstart-esp8266
  import_url: github://libretiny-eu/esphome-kickstart/yaml/import-esp8266.yaml@master

packages:
  base: !include kickstart-base-esp.yaml

esp8266:
  board: nodemcuv2

select:
  - platform: template
    id: !extend pin
    options:
      - Select PIN
      - D0
      - D1
      - D2
      - D3
      - D4
      - D5
      - D6
      - D7
      - D8
      - D9
      - D10
