substitutions:
  name: kickstart-esp8266
  import_url: github://libretiny-eu/esphome-kickstart/yaml/import-esp8266.yaml@master

packages:
  base: !include kickstart-base-esp.yaml

esp8266:
  board: nodemcuv2

select:
  - platform: template
    id: !extend pin
    options:
      - Select PIN
      - D0
      - D1 / SCL
      - D2 / SDA
      - D3
      - D4
      - D5 / SCK
      - D6 / MISO
      - D7 / MOSI
      - D8 / SS
      - D9
      - D10
