substitutions:
  name: kickstart-ln882hki
  import_url: github://libretiny-eu/esphome-kickstart/yaml/import-ln882hki.yaml@master

packages:
  base: !include kickstart-base.yaml

ln882x:
  board: generic-ln882hki
  framework:
    version: dev
    loglevel: debug

select:
  - platform: template
    id: !extend pin
    options:
      - Select PIN
      - PA00 / ADC2 / I2C0_SCL / I2C0_SDA
      - PA01 / ADC3 / SWDIO / I2C0_SCL / I2C0_SDA
      - PA02 / UART0_TX / I2C0_SCL / I2C0_SDA
      - PA03 / UART0_RX / I2C0_SCL / I2C0_SDA
      - PA04 / ADC4 / SWCLK / I2C0_SCL / I2C0_SDA
      - PA05 / I2C0_SCL / I2C0_SDA
      - PA06 / SD_D2 / I2C0_SCL / I2C0_SDA
      - PA07 / SD_D3 / I2S0_RX / I2C0_SCL / I2C0_SDA
      - PA08 / BOOT0 / SD_CMD / I2S0_WS / I2C0_SCL / I2C0_SDA
      - PA09 / BOOT1 / SD_CLK / I2S0_SCLK / I2C0_SCL / I2C0_SDA
      - PA10 / SD_D0 / I2S0_TX / I2C0_SCL / I2C0_SDA
      - PA11 / SD_D1 / I2C0_SCL / I2C0_SDA
      - PA12 / I2C0_SCL / I2C0_SDA
      - PB03 / ADC5 / I2C0_SCL / I2C0_SDA
      - PB04 / ADC6 / I2C0_SCL / I2C0_SDA
      - PB05 / ADC7 / I2C0_SCL / I2C0_SDA
      - PB06 / I2C0_SCL / I2C0_SDA
      - PB07 / I2C0_SCL / I2C0_SDA
      - PB08 / UART1_RX / I2C0_SCL / I2C0_SDA
      - PB09 / UART1_TX / I2C0_SCL / I2C0_SDA
