substitutions:
  name: kickstart-esp32
  import_url: github://libretiny-eu/esphome-kickstart/yaml/import-esp32.yaml@master

packages:
  base: !include kickstart-base-esp.yaml

esp32:
  board: nodemcu-32s

select:
  - platform: template
    id: !extend pin
    options:
      - Select PIN
      - GPIO0,
      - GPIO2,
      - GPIO4,
      - GPIO5,
      - GPIO12,
      - GPIO13,
      - GPIO14,
      - GPIO15,
      - GPIO18,
      - GPIO19,
      - GPIO21,
      - GPIO22,
      - GPIO23,
      - GPIO25,
      - GPIO26,
      - GPIO27,
      - GPIO32,
      - GPIO33,
